# Site settings
title: "Jung Hyun Lee Resume"
description: "Resume page for JHLee"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Junghyun Lee"
resume_title:                   "Student, developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "ljwh123161@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(+82)10-5515-8646"
resume_contact_address:         "Korea"

# resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am a student who earned a bachelor's degree from Yonsei University, Korea. I have experience with Fronted Development, Backend Development, and Deep Learning techniques. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/ljwh1231/ljwh1231.github.io/"
  resume_twitter_url:           "http://twitter.com/hyunbu0101"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/lee.junghyun.58"
  resume_linkedin_url:          "https://www.linkedin.com/in/junghyun-lee-2112a8189/"
  resume_instagram_url:         "https://www.instagram.com/jung__hyun.lee/"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
